version: "3"
services:
  covid-panel:
    container_name: 'covid-panel'
    command: bash -c "jupyter lab --notebook-dir=/home/covid-panel --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    build: .
    ports:
      - '8888:8888'
    volumes:
      - ./:/home/covid-panel
